name: Helm Fineract Frontend
description: Dispatch deployment workflow.
inputs:
  GA_TOKEN:
    description: The password to download artifact.
    required: true
  RUN_ID:
    description: The github run id.
    required: true
  REF:
    description: The github branch reference
    required: true
  DISPATCH_REPO:
    description: The name of the Fineract Frontend app repository.
    required: true
  
runs:
  using: composite
  steps:
  - name: Trigger Workflow in Another Repository
    shell: bash
    run: | 
      curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.GA_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/one-acre-fund/${{ inputs.DISPATCH_REPO }}/actions/workflows/deploy.yml/dispatches \
        -d "{\"ref\": \"${{ inputs.REF }}\", \"inputs\": {\"run_id\": \"${{ inputs.RUN_ID }}\"}}"