apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineract-frontend
  labels:
    app: fineract-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fineract-frontend
  template:
    metadata:
      labels:
        app: fineract-frontend
    spec:
      containers:
      - name: fineract-ui
        image: oaftech.azurecr.io/oneacrefund/fineract-frontend-v2:7d242bb2d53b84be7b60627b69138e4e4c2eceef
        env:
        - name: HOST_HOME_URL
          value: "http://65.108.247.228:31506/home"
        ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https

      imagePullSecrets:
      - name: imagecred