server {
  listen 80;
  sendfile on;
  default_type application/octet-stream;

  root /usr/share/nginx/html;

  location = /assets/env.js {
    add_header Cache-Control "no-store, no-cache, must-revalidate";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html =404;
  }
}
