name: Helm Fineract Frontend
description: GitHub Action for deploying ingresses.

inputs:
  ACR_REGISTRY:
    description: The Azure Container Registry.
    required: true
  ACR_PULL_PASSWORD:
    description: The password for the Azure Container Registry.
    required: true
  ACR_PULL_USERNAME:
    description: The username for the Azure Container Registry.
    required: true
  NAMESPACE:
    description: The namespace to deploy the ingresses.
    required: true
  FINERACT_API_URL:
    description: The URL of the Fineract API.
    required: true
  FINERACT_AUTH_URL:
    description: The URL of the Fineract authentication service.
    required: true
  FINERACT_BASE_URL:
    description: The base URL of the Fineract frontend.
    required: true
  FINERACT_HOST_HOME_URL:
    description: The URL of the Fineract home page.
    required: true
  FINERACT_KEYCLOAK_API_URL:
    description: The URL of the Keycloak API.
    required: true
  FINERACT_KEYCLOAK_AUTH_SERVER_URL:
    description: The URL of the Keycloak authentication server.
    required: true
  FINERACT_KEYCLOAK_CLIENT_ID:
    description: The client ID of the Keycloak client.
    required: true
  FINERACT_KEYCLOAK_TOKEN_URL:
    description: The Token URL of the Keycloak client.
    required: true
  FINERACT_KEYCLOAK_REALM:
    description: The realm of the Keycloak client.
    required: true
  FINERACT_PROXY_HTTP_PORT:
    description: The HTTP port of the Fineract proxy.
    required: true
  FINERACT_PROXY_HTTPS_PORT:
    description: The HTTPS port of the Fineract proxy.
    required: true
  FINERACT_PROXY_URL:
    description: The URL of the Fineract proxy.
    required: true
  RELEASE_NAME:
    description: The name of the Helm release.
    required: true
  REPLICAS:
    description: The number of replicas to deploy.
    required: true
  MATOMO_SITE_URL:
    description: The URL of the Matomo site.
    required: true
  MATOMO_SITE_ID:
    description: The ID of the Matomo site.
    required: true
  SENTRY_DSN:
    description: The Sentry DSN.
    required: true

runs:
  using: composite
  steps:
    - name: Create Values File
      run: |
        cat <<EOF > "${{ github.workspace }}/fineract-values.yaml"
        commonconfig:
          FINERACT_KEYCLOAK_REALM: "${{ inputs.FINERACT_KEYCLOAK_REALM }}"
          FINERACT_KEYCLOAK_AUTH_SERVER_URL: "${{ inputs.FINERACT_KEYCLOAK_AUTH_SERVER_URL }}"
          FINERACT_PROXY_URL: "https://${{ inputs.FINERACT_PROXY_URL }}:${{ inputs.FINERACT_PROXY_HTTPS_PORT }}"
          FINERACT_KEYCLOAK_CLIENT_ID: "${{ inputs.FINERACT_KEYCLOAK_CLIENT_ID }}"
          FINERACT_KEYCLOAK_TOKEN_URL: "${{ inputs.FINERACT_KEYCLOAK_TOKEN_URL }}"
          FINERACT_KEYCLOAK_PUBLIC_CLIENT: true
          FINERACT_KEYCLOAK_API_URL: "${{ inputs.FINERACT_KEYCLOAK_API_URL }}"
          AUTH_SERVER_URL: "${{ inputs.FINERACT_AUTH_URL }}"
          FINERACT_API_URL: "${{ inputs.FINERACT_API_URL }}"
          HOST_HOME_URL: "${{ inputs.FINERACT_HOST_HOME_URL }}"
          MATOMO_SITE_URL: "${{ inputs.MATOMO_SITE_URL }}"
          MATOMO_SITE_ID: "${{ inputs.MATOMO_SITE_ID }}"
          SENTRY_DSN: "${{ inputs.SENTRY_DSN }}"

        initContainers:
          - name: wait-for-fineract-backend
            image: busybox
            command: ['sh', '-c', 'until wget -q -O- http://${{ inputs.FINERACT_PROXY_URL }}:${{ inputs.FINERACT_PROXY_HTTP_PORT }}/fineract-provider/actuator/health; do echo waiting for fineract backend; sleep 2; done;']

        replicaCount: ${{ inputs.REPLICAS }}
        EOF
      shell: bash

    - name: Helm Install Fineract Frontend
      run: |
        export HELM_EXPERIMENTAL_OCI=1
        echo "${{ inputs.ACR_PULL_PASSWORD }}" | helm registry login ${{ inputs.ACR_REGISTRY }} --username "${{ inputs.ACR_PULL_USERNAME }}" --password-stdin

        helm upgrade --install \
          "${{ inputs.RELEASE_NAME }}" \
          --values "${{ github.workspace }}/deployment/values.yaml" \
          --values "${{ github.workspace }}/fineract-values.yaml" \
          --namespace "${{ inputs.NAMESPACE }}" \
          --debug --wait \
          oci://${{ inputs.ACR_REGISTRY }}/helm/fineract-frontend
      shell: bash
