// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.mifos_x.version,
  hash: env.mifos_x.hash,
  // For connecting to server running elsewhere update the tenant identifier
  fineractPlatformTenantId: window['env']['fineractPlatformTenantId'] || 'default',
  // For connecting to others servers running elsewhere update the base API URL
  baseApiUrls: window['env']['fineractApiUrls'] ||
    'https://loans.test.oneacrefund.org,https://loans.qa.oneacrefund.org,https://loans.oneacrefund.org',
  // For connecting to server running elsewhere set the base API URL
  baseApiUrl: window['env']['fineractApiUrl'] || 'https://loans.oneacrefund.org',
  allowServerSwitch: env.allow_switching_backend_instance,
  apiProvider: window['env']['apiProvider'] || '/fineract-provider/api',
  apiVersion: window['env']['apiVersion'] || '/v1',
  serverUrl: '',
  oauth: {
    enabled: true,  // For connecting to Mifos X using OAuth2 Authentication change the value to true
    serverUrl: 'https://accounts.test.oneacrefund.org',
    realm:'OneAcreFund',
    client_id:'fineract',
    redirectUri: window['env']['homeURL'] || 'http://localhost:4200/home'
  },
  defaultLanguage: window['env']['defaultLanguage'] || 'en-US',
  supportedLanguages: window['env']['supportedLanguages'] || 'en-US,fr-FR',
  matomoSiteId:3,
  matomoSiteHost:'https://analytics.oneacrefund.org',
};

// Server URL
environment.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}${environment.apiVersion}`;
//environment.oauth.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}`;
