image:
  # Fineract frontend v2 image name
  name: "952409747009.dkr.ecr.eu-west-1.amazonaws.com/oneacrefund/fineract-frontend-v2"
  # Fineract Frontend v2 image tag placeholder that will be replaced in Azure pipeline task
  tag: "oneacrefund"
