commonconfig:
  FINERACT_KEYCLOAK_CLIENT_ID: fineract
  FINERACT_KEYCLOAK_PUBLIC_CLIENT: "true"
  FINERACT_KEYCLOAK_REALM: OneAcreFund
  FINERACT_PROXY_URL: https://fineract-fineract-backend-fineractrest:8443
  MATOMO_SITE_URL: https://analytics.oneacrefund.org
  SENTRY_DSN: https://de303153328352a5b50dfdd84d381428@o454511.ingest.us.sentry.io/4508318875844608

image:
  name: oaftech.azurecr.io/oneacrefund/fineract-frontend-v2

initContainers:
  - name: wait-for-fineract-backend
    image: busybox
    command:
      - sh
      - -c
      - |
        until wget -q -O - http://fineract-fineract-backend-fineractrest:8080/fineract-provider/actuator/health;
        do echo waiting for fineract backend; sleep 2; done;
