image:
  name: oaftech.azurecr.io/oneacrefund/fineract-frontend-v2

initContainers:
  - name: wait-for-fineract-backend
    image: busybox
    command:
      - sh
      - -c
      - |
        until wget -q -O - http://fineract-fineract-backend-fineractrest:8080/fineract-provider/actuator/health;
        do echo waiting for fineract backend; sleep 2; done;

imagePullSecrets:
  - name: acr-pull-secret