name: Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      k8s_url:
        required: true
        type: string
      k8s_secret:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - uses: one-acre-fund/oaf-actions/helm_setup@main
        with:
          ARTIFACT_NAME: "fineract-frontend-v2"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RUN_ID: "${{ github.run_id }}"
          CI_REPOSITORY: "${{ github.repository }}"
          K8S_URL: "${{ inputs.k8s_url }}"
          K8S_SECRET: "${{ inputs.k8s_secret }}"

      - uses: "./.github/actions/helm_fineract_frontend"
        with:
          NAMESPACE: "${{ vars.NAMESPACE }}"
          ACR_PULL_PASSWORD: "${{ secrets.ACR_PULL_PASSWORD }}"
          ACR_PULL_USERNAME: "${{ vars.ACR_PULL_USERNAME }}"
          REPLICAS: "${{ vars.REPLICAS }}"
          RELEASE_NAME: "${{ vars.RELEASE_NAME }}"
          FINERACT_PROXY_URL: "${{ vars.FINERACT_PROXY_URL }}"
          FINERACT_PROXY_HTTPS_PORT: "${{ vars.FINERACT_PROXY_HTTPS_PORT }}"
          FINERACT_PROXY_HTTP_PORT: "${{ vars.FINERACT_PROXY_HTTP_PORT }}"
          FINERACT_KEYCLOAK_REALM: "${{ vars.FINERACT_KEYCLOAK_REALM }}"
          FINERACT_KEYCLOAK_CLIENT_ID: "${{ vars.FINERACT_KEYCLOAK_CLIENT_ID }}"
          FINERACT_KEYCLOAK_TOKEN_URL: "${{ vars.FINERACT_KEYCLOAK_TOKEN_URL }}"
          FINERACT_KEYCLOAK_AUTH_SERVER_URL: "${{ vars.FINERACT_KEYCLOAK_AUTH_SERVER_URL }}"
          FINERACT_KEYCLOAK_API_URL: "${{ vars.FINERACT_KEYCLOAK_API_URL }}"
          FINERACT_HOST_HOME_URL: "${{ vars.FINERACT_HOST_HOME_URL }}"
          FINERACT_BASE_URL: "${{ vars.FINERACT_BASE_URL }}"
          FINERACT_AUTH_URL: "${{ vars.FINERACT_AUTH_URL }}"
          FINERACT_API_URL: "${{ vars.FINERACT_API_URL }}"
          MATOMO_SITE_ID: "${{ vars.MATOMO_SITE_ID }}"
          MATOMO_SITE_URL: "${{ vars.MATOMO_SITE_URL }}"
          SENTRY_DSN: "${{ secrets.SENTRY_DSN }}"
