      name: Lint

      on: [push, pull_request]

      jobs:
        eslint:
          runs-on: ubuntu-latest

          steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '18.x'

          - name: Install dependencies
            run: npm install

          - name: Run ESLint
            run: npx eslint . --ext .ts,.html

          - name: Run ESLint with detailed output
            run: npx eslint . --ext .ts,.html --format stylish
